### PR TITLE
Added solutions to LAB assignment for ITPC_14(OOPS)

### PR DESCRIPTION
**Pull request by harshvardhan2804**
HI , I am harshvardhan from IT-A added solutions to the lab assignments for the course ITPC-14(object-oriented programming using c++) along with some extra questions given by the course instructor .

### CODE REVIEW

**Comment by GetPsyched** [comment]
Hey! Thanks a lot for the contribution.
However, I want you to make a few subtle changes:
- Bring all the `main.cpp`s one level back and rename them in a short version of the problem that it solves. (Eg. `pallindrome.cpp`, `count.cpp`)
- Add question PDFs in each experiment folder

**Comment by GetPsyched** [comment]
For reference, take a look at [CSIR11 - BOP](https://github.com/GetPsyched/B.Tech-Assignments/tree/main/CSIR11%20-%20BOP)

**Comment by harshvardhan2804** [comment]
Hi sir I have modified the names of files and also added the lab manuals fo exp-1 to exp-5 . Sorry i don't have manual for exp-6 as they were dictated by instructor during course but questions are self explanatory.

**Comment by GetPsyched** [comment]
Looks great!
Just a few file name conventions that this repo follows need to be looked at:
- Rename `ITPC-14 - OOPS` to `ITPC14 - OOPS` (basically removing one hyphen)
- Rename all `EXP-#` folders to `Experiment #` (`#` being the experiment number)
- Rename the PDFs to the same name as the parent folder. So, something like `Experiment 1.pdf`, etc.

**Comment by harshvardhan2804** [comment]
> Looks great! Just a few file name conventions that this repo follows need to be looked at:
> 
> * Rename `ITPC-14 - OOPS` to `ITPC14 - OOPS` (basically removing one hyphen)
> * Rename all `EXP-#` folders to `Experiment #` (`#` being the experiment number)
> * Rename the PDFs to the same name as the parent folder. So, something like `Experiment 1.pdf`, etc.

All the assigned changes has been successfully  implemented .

**Comment by GetPsyched** [comment]
Awesome! Thanks again for the contribution. It will help a ton with [NKSSS](https://github.com/NIT-KKR-Student-Support-System).

**Pull request merged**
